# Generated by Django 4.2.10 on 2024-05-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='title',
            new_name='name',
        ),
    ]
