# Generated by Django 4.2.10 on 2024-05-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_productcategory_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
