# Generated by Django 4.2.10 on 2024-05-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
