# Generated by Django 4.2.10 on 2024-05-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_category_remove_product_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
