# Generated by Django 4.2.10 on 2024-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_slug_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
    ]
