# Generated by Django 4.2.10 on 2024-07-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
