# Generated by Django 4.2.10 on 2024-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='customeraddressId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='OrderId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderItemId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='ProductCategoryId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='ProductRatingId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='UserId',
            new_name='id',
        ),
    ]
