# Generated by Django 4.2.10 on 2024-08-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
